"""Where the process finds its versioned artifacts on disk.

In a source checkout the repo root is derived from this file's location; in a
container the package lives in site-packages, so the image sets ``DW_REPO_ROOT``
(``/app``) and ships ``configs/``, ``evals/fixtures/`` and ``contracts/release/``
at that root.

Every path the composition root reads is named here rather than spelled inline,
so a deployment that relocates one file changes one line.
"""

from __future__ import annotations

import os
from pathlib import Path

from dw_agent_runtime.release import release_manifest_ref as _read_release_manifest_ref
from dw_supply_chain.policy_files import (
    ADVANCE_PRODUCT_CASE_WORKER_FILE,
    FOLLOW_UP_POLICY_FILE,
    PRODUCT_ACTION_DUTIES_POLICY_FILE,
    PRODUCT_APPROVALS_POLICY_FILE,
    PRODUCT_SIGNOFF_WORKER_FILE,
    SLA_POLICY_FILE,
    STEP_PREPARATION_POLICY_FILE,
    STEP_PREPARATION_WORKER_FILE,
)

REPO_ROOT = Path(os.environ.get("DW_REPO_ROOT", str(Path(__file__).resolve().parents[5])))

CONFIGS = REPO_ROOT / "configs"
MODEL_PROFILES_DIR = CONFIGS / "models"
PROMPTS_DIR = CONFIGS / "prompts"
TOOL_SPECS_DIR = CONFIGS / "tools"
TOOLSETS_DIR = CONFIGS / "toolsets"
WORKERS_DIR = CONFIGS / "workers"
POLICIES_DIR = CONFIGS / "policies"

# The platform's own user-facing words, versioned like a prompt bundle so a
# deployment can change them without a release.
# 1.4.0 is 1.3.0 verbatim plus the context-compaction text; a worker that wires
# compaction refuses to start on anything older.
RUNTIME_COPY_CONFIG = CONFIGS / "copy" / "runtime@1.6.0.yaml"
WORKER_RUN_POLICY = POLICIES_DIR / "worker_runs@1.0.0.yaml"
ATTACHMENT_POLICY = POLICIES_DIR / "attachment_ingest@1.1.0.yaml"
SUPPLY_CHAIN_SLA_POLICY = POLICIES_DIR / SLA_POLICY_FILE
SUPPLY_CHAIN_FOLLOW_UP_POLICY = POLICIES_DIR / FOLLOW_UP_POLICY_FILE
SUPPLY_CHAIN_APPROVAL_MATRIX_POLICY = POLICIES_DIR / "supply_chain_approval_matrix@1.0.0.yaml"
SUPPLY_CHAIN_BRIEF_POLICY = POLICIES_DIR / "supply_chain_brief@1.1.0.yaml"
SUPPLY_CHAIN_ACTION_DUTIES = POLICIES_DIR / "supply_chain_action_duties@1.2.0.yaml"
SUPPLY_CHAIN_PACKAGING_POLICY = POLICIES_DIR / "supply_chain_packaging@1.0.0.yaml"
# BM04 as fields (ADR 0026): the schema of a profile's attributes, per tenant.
SUPPLY_CHAIN_BM04_SCHEMA = POLICIES_DIR / "supply_chain_bm04_schema@1.0.0.yaml"
# Document templates (ticket ai-automation/03): the platform layer, loaded at
# start; a tenant's own versions come from storage at run time.
DOC_TEMPLATES_DIR = POLICIES_DIR.parent / "doc_templates"
SUPPLY_CHAIN_PRODUCT_ACTION_DUTIES = POLICIES_DIR / PRODUCT_ACTION_DUTIES_POLICY_FILE
SUPPLY_CHAIN_PRODUCT_APPROVALS = POLICIES_DIR / PRODUCT_APPROVALS_POLICY_FILE
SUPPLY_CHAIN_ADVANCE_CASE_WORKER = WORKERS_DIR / "supply_chain_advance_case.yaml"
SUPPLY_CHAIN_ADVANCE_PRODUCT_CASE_WORKER = WORKERS_DIR / ADVANCE_PRODUCT_CASE_WORKER_FILE
SUPPLY_CHAIN_PRODUCT_SIGNOFF_WORKER = WORKERS_DIR / PRODUCT_SIGNOFF_WORKER_FILE
# Step preparation (ticket ai-automation/05): which steps AI prepares, and
# the worker whose runs a decision on the web resumes.
SUPPLY_CHAIN_STEP_PREPARATION_POLICY = POLICIES_DIR / STEP_PREPARATION_POLICY_FILE
SUPPLY_CHAIN_STEP_PREPARATION_WORKER = WORKERS_DIR / STEP_PREPARATION_WORKER_FILE

MOCK_MODEL_FIXTURES = REPO_ROOT / "evals" / "fixtures" / "mock_model"


def release_manifest_ref() -> str:
    """The content-addressed release this process is serving.

    Generated by ``make release-manifest``; every run records it so a result can
    be traced back to the exact artifact set that produced it. Absent only in
    un-released development trees. Read by `dw_agent_runtime.release`, the one
    reader the worker uses too.
    """
    return _read_release_manifest_ref(REPO_ROOT)
