"""SQLAlchemy Core table definitions for the supply_chain schema.

Query-building only — the migration is schema authority, so no CHECK
constraint or trigger is repeated here; this mirrors `dw_platform.adapters.
persistence.tables`'s own convention for the same reason.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

from dw_kernel.naming import NAMING_CONVENTION

metadata = sa.MetaData(schema="supply_chain", naming_convention=NAMING_CONVENTION)

# The supplier master record (a0035e9faf32): one per normalized name per
# tenant and workspace. `normalized_name` is generated by the database.
suppliers = sa.Table(
    "suppliers",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("name", sa.Text, nullable=False),
    sa.Column(
        "normalized_name", sa.Text, sa.Computed("supply_chain.normalize_supplier_name(name)")
    ),
    sa.Column("code", sa.Text, nullable=True),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

po_cases = sa.Table(
    "po_cases",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    # NULL only while the case awaits its PO (`order_requested`), or cancelled
    # from there (`ck_po_cases_po_reference`, ADR 0017).
    sa.Column("po_reference", sa.Text, nullable=True),
    # The supplier's stored name, kept equal to it by the FK on both columns.
    sa.Column("supplier_id", UUID(as_uuid=True), nullable=False),
    sa.Column("supplier_name", sa.Text, nullable=False),
    sa.Column("state", sa.Text, nullable=False, server_default="po_created"),
    sa.Column("interrupted_state", sa.Text, nullable=True),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column(
        "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column("version", sa.Integer, nullable=False, server_default="1"),
    sa.Column("order_kind", sa.Text, nullable=False),
    # Set when ĐẶT HÀNG opened the case, with the product case's PIC and
    # Category stamped beside it (migration 84d1c1946b44).
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("pic_user_id", UUID(as_uuid=True), nullable=True),
    sa.Column("category", sa.Text, nullable=True),
    # Commercial terms (82221a867e62, ADR 0026): read and written only by
    # `commercial_repository`, behind `supply_chain.commercial.*`.
    sa.Column("currency", sa.Text, nullable=True),
    sa.Column("incoterm", sa.Text, nullable=True),
    sa.Column("payment_terms", sa.Text, nullable=True),
    sa.Column("deposit_percent", sa.Numeric(5, 2), nullable=True),
    sa.Column("expected_delivery_date", sa.Date, nullable=True),
)

# One planned line of a PO case: a SKU and how many (NULL until `create_po`
# when the SKU's planned quantity was open).
po_case_lines = sa.Table(
    "po_case_lines",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("sku_id", UUID(as_uuid=True), nullable=False),
    sa.Column("quantity", sa.Integer, nullable=True),
    # NULL until someone with `supply_chain.commercial.write` sets it.
    sa.Column("unit_price", sa.Numeric(18, 4), nullable=True),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

supplier_updates = sa.Table(
    "supplier_updates",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), sa.ForeignKey("po_cases.id"), nullable=False),
    sa.Column("raw_text", sa.Text, nullable=False),
    sa.Column("event_type", sa.Text, nullable=False),
    sa.Column("affected_po", sa.Text, nullable=True),
    sa.Column("delay_days", sa.Integer, nullable=True),
    sa.Column("reason", sa.Text, nullable=False),
    sa.Column("proposed_action", sa.Text, nullable=False),
    sa.Column("confidence", sa.Numeric(3, 2), nullable=False),
    sa.Column("source_ref", sa.Text, nullable=False),
    sa.Column("requires_confirmation", sa.Boolean, nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

po_case_state_transitions = sa.Table(
    "po_case_state_transitions",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), sa.ForeignKey("po_cases.id"), nullable=False),
    sa.Column("from_state", sa.Text, nullable=False),
    sa.Column("to_state", sa.Text, nullable=False),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column(
        "occurred_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

delay_impact_analyses = sa.Table(
    "delay_impact_analyses",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), sa.ForeignKey("po_cases.id"), nullable=False),
    sa.Column(
        "supplier_update_id",
        UUID(as_uuid=True),
        sa.ForeignKey("supplier_updates.id"),
        nullable=False,
    ),
    sa.Column("delay_days", sa.Integer, nullable=False),
    sa.Column("impacted_milestones", JSONB, nullable=False),
    sa.Column("assumptions", JSONB, nullable=False),
    sa.Column("mitigation_options", JSONB, nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

follow_ups = sa.Table(
    "follow_ups",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    # Exactly one of the two is set (`ck_follow_ups_one_case`).
    sa.Column("po_case_id", UUID(as_uuid=True), sa.ForeignKey("po_cases.id"), nullable=True),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("kind", sa.Text, nullable=False),
    sa.Column("episode", sa.Text, nullable=False),
    sa.Column("milestone", sa.Text, nullable=True),
    sa.Column("days", sa.Integer, nullable=False),
    sa.Column("limit_days", sa.Integer, nullable=True),
    sa.Column("recipient_scopes", JSONB, nullable=False),
    # The PIC stamped when it opened, if the policy routed its kind to `pic`.
    sa.Column("recipient_user_id", UUID(as_uuid=True), nullable=True),
    sa.Column("status", sa.Text, nullable=False, server_default="open"),
    sa.Column(
        "opened_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column("notified_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("closed_by", UUID(as_uuid=True), nullable=True),
    sa.Column("close_note", sa.Text, nullable=True),
)

case_documents = sa.Table(
    "case_documents",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    # Exactly one of the two is set (`ck_case_documents_one_case`).
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("doc_type", sa.Text, nullable=False),
    sa.Column("object_key", sa.Text, nullable=False),
    sa.Column("filename", sa.Text, nullable=False),
    sa.Column("content_type", sa.Text, nullable=False),
    sa.Column("size_bytes", sa.BigInteger, nullable=False),
    sa.Column("sha256", sa.Text, nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("uploaded_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "uploaded_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    # `uploaded`, or `ai_prepared` naming the draft it came from (cbebad572558).
    sa.Column("origin", sa.Text, nullable=False, server_default="uploaded"),
    sa.Column("draft_id", UUID(as_uuid=True), nullable=True),
)

product_dev_cases = sa.Table(
    "product_dev_cases",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("proposal_code", sa.Text, nullable=False),
    sa.Column("product_name", sa.Text, nullable=False),
    sa.Column("category", sa.Text, nullable=False),
    # NULL until step 2 names the supplier; then as `po_cases`.
    sa.Column("supplier_id", UUID(as_uuid=True), nullable=True),
    sa.Column("supplier_name", sa.Text, nullable=True),
    sa.Column("pic_user_id", UUID(as_uuid=True), nullable=False),
    sa.Column("state", sa.Text, nullable=False, server_default="proposed"),
    sa.Column("interrupted_state", sa.Text, nullable=True),
    sa.Column("sample_round", sa.Integer, nullable=False, server_default="0"),
    # How many times the case was submitted for sign-off (76bd1b5fc546).
    sa.Column("signoff_round", sa.Integer, nullable=False, server_default="0"),
    sa.Column("version", sa.Integer, nullable=False, server_default="1"),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column(
        "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

product_dev_case_state_transitions = sa.Table(
    "product_dev_case_state_transitions",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("action", sa.Text, nullable=False),
    sa.Column("from_state", sa.Text, nullable=True),
    sa.Column("to_state", sa.Text, nullable=False),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("actor_id", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "occurred_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    # The paper of steps 7 and 8 (3fc6599ecd5e); a round's paper is on the round.
    sa.Column("document_id", UUID(as_uuid=True), nullable=True),
)

product_sample_rounds = sa.Table(
    "product_sample_rounds",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("round_no", sa.Integer, nullable=False),
    sa.Column(
        "opened_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column("opened_by", UUID(as_uuid=True), nullable=False),
    sa.Column("result", sa.Text, nullable=True),
    sa.Column("evaluation_document_id", UUID(as_uuid=True), nullable=True),
    sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("closed_by", UUID(as_uuid=True), nullable=True),
)

sample_revision_requests = sa.Table(
    "sample_revision_requests",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("round_no", sa.Integer, nullable=False),
    sa.Column("revision_document_id", UUID(as_uuid=True), nullable=False),
    sa.Column("requested_changes", sa.Text, nullable=False),
    sa.Column("sent_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "sent_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# Step 9 (76bd1b5fc546): a case's official item code, unique per tenant, and
# its SKUs, each unique per tenant and under the case's own item code.
item_codes = sa.Table(
    "item_codes",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("code", sa.Text, nullable=False),
    sa.Column("issued_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "issued_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column(
        "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

skus = sa.Table(
    "skus",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("item_code_id", UUID(as_uuid=True), nullable=False),
    sa.Column("sku_code", sa.Text, nullable=False),
    sa.Column("variant_label", sa.Text, nullable=False),
    sa.Column("planned_quantity", sa.Integer, nullable=True),
    sa.Column("added_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "added_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A chat proposal being drafted (zalo-channel ticket 04): one open draft per
# person, workspace and channel; consumed when it becomes a case.
proposal_drafts = sa.Table(
    "proposal_drafts",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("user_id", UUID(as_uuid=True), nullable=False),
    sa.Column("channel", sa.Text, nullable=False),
    sa.Column("draft", JSONB, nullable=False),
    sa.Column("draft_version", sa.Integer, nullable=False),
    sa.Column("summarized_version", sa.Integer, nullable=True),
    sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column(
        "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# Step 12's colour, packaging and pre-production sub-flow (slice PK): one row
# per PO case, and its history.
packaging_designs = sa.Table(
    "packaging_designs",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("colour_status", sa.Text, nullable=False),
    sa.Column("design_status", sa.Text, nullable=False),
    sa.Column("pre_production_sample_received_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("pre_production_test", sa.Text, nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
    sa.Column(
        "updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

packaging_design_events = sa.Table(
    "packaging_design_events",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("action", sa.Text, nullable=False),
    sa.Column("actor_id", UUID(as_uuid=True), nullable=False),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("note", sa.Text, nullable=True),
    sa.Column("document_id", UUID(as_uuid=True), nullable=True),
    sa.Column(
        "occurred_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)


# BM04 as fields (82221a867e62, ADR 0026): one row per save, append-only.
product_profiles = sa.Table(
    "product_profiles",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("unit_price", sa.Numeric(18, 4), nullable=True),
    sa.Column("currency", sa.Text, nullable=True),
    sa.Column("moq", sa.Integer, nullable=True),
    sa.Column("lead_time_days", sa.Integer, nullable=True),
    sa.Column("incoterm", sa.Text, nullable=True),
    sa.Column("attributes", JSONB, nullable=False),
    sa.Column("schema_version", sa.Text, nullable=False),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A PO case's deposit and final payment, one row per version, append-only.
po_payments = sa.Table(
    "po_payments",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("kind", sa.Text, nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("amount", sa.Numeric(18, 2), nullable=False),
    sa.Column("currency", sa.Text, nullable=False),
    sa.Column("due_date", sa.Date, nullable=True),
    sa.Column("paid_on", sa.Date, nullable=True),
    sa.Column("document_id", UUID(as_uuid=True), nullable=True),
    sa.Column("recorded_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "recorded_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A supplier's contact person and bank account, append-only versions.
supplier_contacts = sa.Table(
    "supplier_contacts",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("supplier_id", UUID(as_uuid=True), nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("name", sa.Text, nullable=False),
    sa.Column("email", sa.Text, nullable=True),
    sa.Column("phone", sa.Text, nullable=True),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

supplier_bank_accounts = sa.Table(
    "supplier_bank_accounts",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("supplier_id", UUID(as_uuid=True), nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("bank_name", sa.Text, nullable=False),
    sa.Column("account_number", sa.Text, nullable=False),
    sa.Column("account_holder", sa.Text, nullable=False),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A case document read into cited fields (e21dc10d13b5, ADR 0021 amended
# 2026-10-09): one row per (document, prompt version), append-only.
document_extractions = sa.Table(
    "document_extractions",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("document_id", UUID(as_uuid=True), nullable=False),
    sa.Column("doc_type", sa.Text, nullable=False),
    sa.Column("sha256", sa.Text, nullable=False),
    sa.Column("prompt_id", sa.Text, nullable=False),
    sa.Column("prompt_version", sa.Text, nullable=False),
    sa.Column("model_profile", sa.Text, nullable=True),
    sa.Column("status", sa.Text, nullable=False),
    sa.Column("text", sa.Text, nullable=False),
    sa.Column("fields", JSONB, nullable=False),
    sa.Column("gaps", JSONB, nullable=False),
    sa.Column("redactions", sa.Integer, nullable=False),
    sa.Column("error", sa.Text, nullable=True),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# Drafts of a case's documents (cbebad572558, ADR 0025 point 4): one row per
# version, append-only, and at most one decision per version.
document_drafts = sa.Table(
    "document_drafts",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("lineage_id", UUID(as_uuid=True), nullable=False),
    sa.Column("version", sa.Integer, nullable=False),
    sa.Column("doc_type", sa.Text, nullable=False),
    sa.Column("template_id", sa.Text, nullable=False),
    sa.Column("template_version", sa.Text, nullable=False),
    sa.Column("prompt_id", sa.Text, nullable=True),
    sa.Column("prompt_version", sa.Text, nullable=True),
    sa.Column("fields", JSONB, nullable=False),
    sa.Column("gaps", JSONB, nullable=False),
    sa.Column("sources", JSONB, nullable=False),
    sa.Column("content_sha256", sa.Text, nullable=False),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

document_draft_decisions = sa.Table(
    "document_draft_decisions",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("draft_id", UUID(as_uuid=True), nullable=False),
    sa.Column("decision", sa.Text, nullable=False),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("decided_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "decided_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A tenant's own version of a platform document template (tenant-wide).
doc_template_overrides = sa.Table(
    "doc_template_overrides",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("template_id", sa.Text, nullable=False),
    sa.Column("version", sa.Text, nullable=False),
    sa.Column("spec", sa.Text, nullable=False),
    sa.Column("docx", sa.LargeBinary, nullable=False),
    sa.Column("checksum", sa.Text, nullable=False),
    sa.Column("uploaded_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# What each preparation of a step came to (ticket ai-automation/05): one row per
# change, append-only, keyed by the history row that brought the case into the
# step and the policy version it was prepared under.
step_preparations = sa.Table(
    "step_preparations",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("transition_id", UUID(as_uuid=True), nullable=False),
    sa.Column("policy_version", sa.Text, nullable=False),
    sa.Column("action", sa.Text, nullable=False),
    sa.Column("outcome", sa.Text, nullable=False),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("run_id", UUID(as_uuid=True), nullable=True),
    sa.Column("draft_lineages", JSONB, nullable=False),
    sa.Column("recorded_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# Messages to a supplier AI drafts and a person sends (1dc679326cb5, ADR 0029):
# one row per trigger, append-only; "Đã gửi" is a row of its own.
supplier_messages = sa.Table(
    "supplier_messages",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("po_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("purpose", sa.Text, nullable=False),
    sa.Column("status", sa.Text, nullable=False),
    sa.Column("source_key", sa.Text, nullable=False),
    sa.Column("supplier_name", sa.Text, nullable=True),
    sa.Column("recipient_name", sa.Text, nullable=True),
    sa.Column("recipient_email", sa.Text, nullable=True),
    sa.Column("subject", sa.Text, nullable=False),
    sa.Column("body", sa.Text, nullable=False),
    sa.Column("attachments", JSONB, nullable=False),
    sa.Column("citations", JSONB, nullable=False),
    sa.Column("dropped", sa.Integer, nullable=False),
    sa.Column("template_version", sa.Text, nullable=False),
    sa.Column("prompt_id", sa.Text, nullable=False),
    sa.Column("prompt_version", sa.Text, nullable=False),
    sa.Column("model_profile", sa.Text, nullable=True),
    sa.Column("content_sha256", sa.Text, nullable=False),
    sa.Column("created_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

supplier_message_sends = sa.Table(
    "supplier_message_sends",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("message_id", UUID(as_uuid=True), nullable=False),
    sa.Column("content_sha256", sa.Text, nullable=False),
    sa.Column("sent_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "sent_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# A list of proposed products dropped in at step 1, its readings and each row's
# decision (381374b3cb35, ticket ai-automation/08), all append-only.
proposal_lists = sa.Table(
    "proposal_lists",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("filename", sa.Text, nullable=False),
    sa.Column("content_type", sa.Text, nullable=False),
    sa.Column("size_bytes", sa.Integer, nullable=False),
    sa.Column("sha256", sa.Text, nullable=False),
    sa.Column("content", sa.LargeBinary, nullable=False),
    sa.Column("uploaded_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

proposal_list_readings = sa.Table(
    "proposal_list_readings",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("list_id", UUID(as_uuid=True), nullable=False),
    sa.Column("status", sa.Text, nullable=False),
    sa.Column("prompt_id", sa.Text, nullable=False),
    sa.Column("prompt_version", sa.Text, nullable=False),
    sa.Column("model_profile", sa.Text, nullable=True),
    sa.Column("items", JSONB, nullable=False),
    sa.Column("redactions", sa.Integer, nullable=False),
    sa.Column("error", sa.Text, nullable=True),
    sa.Column(
        "created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

proposal_list_decisions = sa.Table(
    "proposal_list_decisions",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("list_id", UUID(as_uuid=True), nullable=False),
    sa.Column("row_index", sa.Integer, nullable=False),
    sa.Column("decision", sa.Text, nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=True),
    sa.Column("reason", sa.Text, nullable=True),
    sa.Column("decided_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "decided_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)

# What R&D measured on a sample round, criterion by criterion (1021f7fe88f0,
# ticket ai-automation/09), append-only; the newest value of a criterion counts.
sample_measurements = sa.Table(
    "sample_measurements",
    metadata,
    sa.Column("id", UUID(as_uuid=True), primary_key=True),
    sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
    sa.Column("workspace_id", UUID(as_uuid=True), nullable=False),
    sa.Column("product_dev_case_id", UUID(as_uuid=True), nullable=False),
    sa.Column("sample_round", sa.Integer, nullable=False),
    sa.Column("criterion", sa.Text, nullable=False),
    sa.Column("value", sa.Text, nullable=False),
    sa.Column("note", sa.Text, nullable=True),
    sa.Column("entered_by", UUID(as_uuid=True), nullable=False),
    sa.Column(
        "entered_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")
    ),
)
